### ISSUE TITLE
Button doesnt work

### ISSUE THREAD

**Issue by dimiii** [emilianox/flow-jira-commit-prefix#9]
It looks like vscode.git has started to return obfuscated `uri` object and and thus the [comparison](https://github.com/emilianox/flow-jira-commit-prefix/blob/master/src/extension.ts#L17) throws an exception:

```
2022-12-16 13:26:21.425 [error] TypeError: Cannot read properties of undefined (reading 'path')
    at /Users/xxxxxxx/.vscode/extensions/emilianox.flow-jira-commit-prefix-0.0.5/out/extension.js:26:66
    at Array.find (<anonymous>)
    at /Users/xxxxxxx/.vscode/extensions/emilianox.flow-jira-commit-prefix-0.0.5/out/extension.js:21:57
    at Generator.next (<anonymous>)
    at /Users/xxxxxxx/.vscode/extensions/emilianox.flow-jira-commit-prefix-0.0.5/out/extension.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxxxxxx/.vscode/extensions/emilianox.flow-jira-commit-prefix-0.0.5/out/extension.js:3:12)
    at /Users/xxxxxxx/.vscode/extensions/emilianox.flow-jira-commit-prefix-0.0.5/out/extension.js:13:98
    at s.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107622)
    at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:108311)
    at u.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
    at u.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
    at u.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
    at u.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at c.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
    at Socket.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:19792)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) flowJiraCommitPrefix.setMessage {"value":"emilianox.flow-jira-commit-prefix","c":"emilianox.flow-jira-commit-prefix"}⏎                     
```

The quickfix is:

``` diff
+                 return Object.values(uri).find(v => repository.rootUri.path  == v?.path)
-                 return repository.rootUri.path === uri._rootUri.path;
```

**Comment by Mariownyou** [comment]
can confirm that button does not work on newest version of vs code

**Comment by Mariownyou** [comment]
@dimiii 
I think this extension is no longer supported. However I found work around.
1. Download [Git Prefix](https://marketplace.visualstudio.com/items?itemName=srmeyers.git-prefix) extension
2. Change **Pattern** option in settings ``(FP-\d+)(.*)``
3. Change **Replacement** option if needed `$1 `

Works absolutely fine for me

**Comment by WaffleBuffer** [comment]
Following @Mariownyou solution with Git Flow (at least most cases of git flow branches) : 
- **Pattern** : (.+\/)(.*)
- **Replacement** : "$2 " (without the quotes but with the extra white space. This works for Jira integration but you may want to set something else)

**Comment by emilianox** [comment]
Hi folks, now it's working again, thank you for your patience. LMK if all runs smoothly :grinning:
